site_name: Coffee Analysis

nav:
  - Overview: index.md
  - Installation: install.md
  - API Reference: api.md

theme:
  name: material
  palette:
    primary: orange
    accent: deep orange

plugins:
  - search
  - mkdocstrings:
      handlers:
        python: 
          options:
            docstring_style: google