name: run-unit-tests

on: push

jobs: 
    build-and-test:

        runs-on: windows-latest
        
        steps: 
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python 3.11
              uses: actions/setup-python@v5
              with:
                python-version: "3.11"

            - name: Install Python Dependencies
              run: | 
                python3 -m pip install --upgrade pip
                python3 -m pip install -r requirements.txt
        
            - name: Test with pytest
              run: | 
                python3 -m pytest -v tests\

            

            