name: Pylint
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matirx.python-version }}

      - name: Install dependencies
        run: |
          python -m install --upgrade pip
          pip install pylint
          if [ -f requirements.txt]; then pip install -r requirements.txt; fi

      - name: Analysing the code
        run: |
          pylint $(git ls-files '*.py')